### ISSUE TITLE
Pinch Zoom

### ISSUE THREAD

**Issue by croossin** [foundry/OpenCVSwiftStitch#13]
Are you able to pinch zoom with this? I have not been successful yet.  I see that you have 
```
 self.scrollView.maximumZoomScale = 4.0
 self.scrollView.minimumZoomScale = 0.5
```
So I figured there might be the ability to zoom. Thanks again!

**Comment by foundry** [comment]
It seems I had not set the scrollView's delegate, so 'viewForZoomingInScrollView' was not being called. I've made a quick fix...
