### ISSUE TITLE
Infinite scrolling

### ISSUE THREAD

**Issue by croossin** [foundry/OpenCVSwiftStitch#14]
Sorry for the question again! Do you think there is an easy way to implement horizontal infinite scrolling? I am tinkering with ```scrollViewDidEndDecelerating``` and can determine that I have reached the right side of the pano, but is there a way to wrap the left side of the pano to the right side and vice versa?  Thanks!

**Comment by foundry** [comment]
The easy way is to scroll across a row of identical imageViews, resetting the scrollview state whenever scolling comes to rest. A useful resource is the WWDC scrollview session from 2011, [Advanced Scrollview Techniques](https://developer.apple.com/videos/play/wwdc2011-104/), and the accompanying sample app [PhotoScroller] (https://developer.apple.com/library/ios/samplecode/PhotoScroller/Introduction/Intro.html).  This is one of a  a great series of scrollview sessions delivered annually by Josh Shaffer and Eliza Block from WWDC 2009-2014: they are all worth watching.

A completely different approach would be to set up an openGL view and map the stitched pano onto a skybox. GLKit has a nice implementation of skyboxes which could help you out. Harder to implement, but will get you closer to a 'seamless' result if you can get the projections right.
