### ISSUE TITLE
OpenCV 3

### ISSUE THREAD

**Issue by croossin** [foundry/OpenCVSwiftStitch#15]
It seems that when downloading the 3.0.0 framework from their site, it downloads the same framework.  How did you get?

**Comment by foundry** [comment]
i'm not sure i understand your question. The link to 'openCV for iOS' on the front page of opencv.org downloads the openCV3.0.0 framework. Confusingly, it is NAMED opencv2, same as the opencv.2.x.x versions.

You can verify the version by checking Headers/core/version.hpp:

v3.0.0  

    #define CV_VERSION_MAJOR    3
    #define CV_VERSION_MINOR    0
    #define CV_VERSION_REVISION 0


v2.4.11  

    #define CV_VERSION_EPOCH    2
    #define CV_VERSION_MAJOR    4
    #define CV_VERSION_MINOR    11
    #define CV_VERSION_REVISION 0

Note they also changed the numbering scheme - annoyingly - so using preprocessor checks for CV_VERSION_MAJOR can easily give you the opposite result you are hoping for.

**Comment by foundry** [comment]
We are installing 2.4.x and 3.1.x via cocoapods now due to broken binaries provided by openCV.org
