### ISSUE TITLE
critical issue

### ISSUE THREAD

**Issue by imranmunirawan** [foundry/OpenCVSwiftStitch#16]
OpenCVSwiftStitch-master/SwiftStitch/UIImage+OpenCV.h:16:9: 'opencv2/opencv.hpp' file not found

**Comment by foundry** [comment]
It looks like you haven't installed openCV. See "installation" in the readme....

You can either install openCV2.x using cocoapods, or download openCV3 from opencv.org directly.

**Comment by mweber7** [comment]
I am getting the same error and I have installed openCV3 as described in the readme.  I am using version 7.3 of Xcode.  I have tried creating my own OpenCV project as well and am getting the same error.  Any ideas?

**Comment by foundry** [comment]
if you follow the error, you will see it occurs here:

<img width="871" alt="screen shot 2016-05-10 at 01 30 50" src="https://cloud.githubusercontent.com/assets/341731/15132225/2d435bfa-164f-11e6-9dcf-bc9873b8d5c1.png">


if you comment the openCV 2.4.x line, uncomment the openCV 3 line, this _may_ give you better results

_HOWEVER_...

Thanks to your question, I have just tested against the latest  build of openCV3.1.0 and even when the lines are correctly un/commented it seems to break with other issues 

_sigh_...

seamless openCV intergration seems a sisyphian task!

I would be obliged if you could send an update how you get on with the latest openCV 3.1.0 iOS build. If there are still issues I will investigate further.

Thanks for the feedback!

**Comment by carloAI2** [comment]
I'm getting the same errors as wells. Did you find a solution to installing OpenCV 3.1.0? My workflow is the following

1. git clone https://github.com/foundry/OpenCVSwiftStitch.git
2. Download opencv2.framework (http://sourceforge.net/projects/opencvlibrary/files/opencv-ios/3.1.0/opencv2.framework.zip/download)
3. Drag opencv2.framework one line underneath the SwitftStich project (also tried in under Frameworks).
4. CMD + B to build.

Error still occurs on #include <opencv2/opencv.hpp> for  UIImage+OpenCV.h.

**Comment by foundry** [comment]
Fixe by installing via cocoapods: https://github.com/foundry/OpenCVSwiftStitch/commit/d2d95dfe412aec533ccb9323915a1d0172a47cee  
  
This version applies a hotfix to enable NEON for arm64 - opencv/opencv@262a52f
