### ISSUE TITLE
can not get the https://github.com/Zi0P4tch0/Specs.git

### ISSUE THREAD

**Issue by playdeme** [foundry/OpenCVSwiftStitch#19]
[!] Unable to add a source with url `https://github.com/Zi0P4tch0/Specs.git` named `zi0p4tch0`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

the error message is above. Can you help take a look? why can't I find the spec? how to fix it?

Thanks

**Comment by foundry** [comment]
The spec is down. I will make a replacement...

**Comment by foundry** [comment]
fixed -https://github.com/foundry/OpenCVSwiftStitch/commit/1a9dd137758b4e8434d6301b8b8e3fa2bf1fac1d

To use 2.4.9:  
- edit the podFile to use 2.4.9.3  
- edit lines 61 and 64 of `stitching.cpp` as indicated for openCV 2.4.x
