### ISSUE TITLE
i'm getting an out of memory crash when stitching 3 images (320px*640px)

### ISSUE THREAD

**Issue by ocnur** [foundry/OpenCVSwiftStitch#21]
stitching...
malloc: *** mach_vm_map(size=2606923776) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
OpenCV Error: Insufficient memory (Failed to allocate 2606919364 bytes) in OutOfMemoryError, file /Users/kyle/code/opensource/opencv/modules/core/src/alloc.cpp, line 52
OpenCV Error: Assertion failed (u != 0) in create, file /Users/kyle/code/opensource/opencv/modules/core/src/matrix.cpp, line 424
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/kyle/code/opensource/opencv/modules/core/src/matrix.cpp:424: error: (-215) u != 0 in function create

**Comment by foundry** [comment]
if you can attach those images i will investigate.

**Comment by ocnur** [comment]
For some reason it goes up to 6344441104 bytes - i am uploading the images

matImage: <UIImage: 0x174097930> size {360, 480} orientation 3 scale 1.000000
matImage: <UIImage: 0x170097cf0> size {360, 480} orientation 3 scale 1.000000
matImage: <UIImage: 0x170098ce0> size {360, 480} orientation 3 scale 1.000000
stitching...
malloc: *** mach_vm_map(size=6344441856) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
OpenCV Error: Insufficient memory (Failed to allocate 6344441104 bytes) in OutOfMemoryError, file /Users/kyle/code/opensource/opencv/modules/core/src/alloc.cpp, line 52
OpenCV Error: Assertion failed (u != 0) in create, file /Users/kyle/code/opensource/opencv/modules/core/src/matrix.cpp, line 424
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/kyle/code/opensource/opencv/modules/core/src/matrix.cpp:424: error: (-215) u != 0 in function create

**Comment by foundry** [comment]
I can't investigate without the actual images. But my guess is that you are not feeding them in with the correct orientation or in the correct order.

**Comment by ocnur** [comment]
what should be the order and orientation?
i want to scan a long document from top to bottom

**Comment by foundry** [comment]
make sure you are following the same order and orientation as per the included sample images

**Comment by ocnur** [comment]
from left to right i get it, right?

**Comment by foundry** [comment]
If you have a long top-to-bottom doc, treat it as a landscape doc (turned sideways) made up of a sequence of portrait images / doc slices

**Comment by foundry** [comment]
try turning it so top is left and read it from left/top to right/bottom. With a good overlap between the slices

**Comment by ocnur** [comment]
yupp that solved the issue. is there a chance to add top-to-bottom stitching? instead of left-to-right?
i will now implement a simple transpose on all the images as i scan them, but it would be great
and your framework is really really awesome!!! i love it

**Comment by maurymarkowitz** [comment]
Given the thread above, is it possible to use the framework in landscape orientation? I suspect the gizmo I want to write will work better in portrait, but it would be nice if it could do both.

**Comment by linkfei** [comment]
Hello ! How to splice multiple images from top to bottom in a vertical direction, instead of a horizontal version of the panorama.

**Comment by jscul** [comment]
My issue was that I was stitching images that were vertical instead of horizontal.

```
image = cv2.rotate(cv2.imread(imagePath), cv2.ROTATE_90_CLOCKWISE)
...
stitched = cv2.rotate(stitched, cv2.ROTATE_90_COUNTERCLOCKWISE)
```

^ this should help if you're looking to do vertical..

**Comment by lucychen0103** [comment]
@jscul Where do you put the code? What's cv2?

**Comment by jscul** [comment]
@lucychen0103 cv2 is an image processing tool. Basically you need to rotate the images to make them horizontal if you're trying to stitch vertical images then rotate that final result back.
