### ISSUE TITLE
Import problems for some users

### ISSUE THREAD

**Issue by maurymarkowitz** [foundry/OpenCVSwiftStitch#22]
A number of users, myself included, have found that including this code in their own programs will cause a run-time error with the string "cvflann::anyimpl::bad_any_cast".

This can be fixed with two identical edits in stitching.h and UIImage+OpenCV.h. Simply change the line that reads:

#import <opencv2/opencv.hpp>

to:

#import <opencv2/stitching.hpp>
#import <opencv2/imgcodecs.hpp>

It appears there is a problem in another part of the OpenCV build, and simply importing just the parts you need avoids it. I didn't think this was worth a pull, but I'd be happy to if you think it's useful.

**Comment by foundry** [comment]
Fixed in #2c6f523
