### ISSUE TITLE
I wanted to make the Twitter chat screenshot look seamless, but downloading the project and loading the chat image crashed.

### ISSUE THREAD

**Issue by CloseServer** [foundry/OpenCVSwiftStitch#23]
![1](https://user-images.githubusercontent.com/12987627/46711384-bc2fe080-cc7e-11e8-8873-cc8146ea4d3a.png)
The prompt message is shown in the figure.

I don't know how to put pictures together from the top down.

**Comment by foundry** [comment]
This implementation can only stitch left-right, not up-down
