### ISSUE TITLE
OpenCV 4 Support

### ISSUE THREAD

**Issue by awcchungster** [foundry/OpenCVSwiftStitch#24]
This repo doesn't look that maintained anymore, but asking anyways. Does anyone have fork or version of this that supports OpenCV 4?

**Comment by foundry** [comment]
Updated for OpenCV 4.3

**Comment by awcchungster** [comment]
Thanks!

**Comment by awcchungster** [comment]
This is another resources I used and found helpful for getting this working.

https://github.com/PacktPublishing/Mastering-OpenCV-4-Third-Edition/tree/master/Chapter_08
