### ISSUE TITLE
opencv pod borken

### ISSUE THREAD

**Issue by sfr106** [foundry/OpenCVSwiftStitch#4]
the source link in the opencv pod is broken

**Comment by foundry** [comment]
There does seem to be an issue with the pod install which I am investigating. Meanwhile you could use the openCV framework (or complete objective-C version of the project) at https://github.com/foundry/OpenCVStitch

**Comment by foundry** [comment]
Fixed, thanks to Zi0P4tch0... we are self-hosting the openCV framework v.2.4.9 as the download links from SourceForge seem to be breaking. Install via the updated podfile...
