### ISSUE TITLE
Linker problems, and some questions

### ISSUE THREAD

**Issue by LauraLaureus** [foundry/OpenCVSwiftStitch#7]
Hi! I'm trying to learn about OpenCV-iOSSwift when I found your project. First of all thanks for developing it. However I have a problem when I try to build it this:

ld: library not found for -lPods
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Searching on Internet It could be a Build Phases/"Link Binary with Libraries" problem, however in this section there is an entry called "libPods.a" and I thougth it's the same library named in two different forms.

So there my questions:
1)Where to change Pods to libPods, in order to fix this bug?
2)How should I change the project to use the bridge with the newest version of OpenCV 3.0 framework, I have already downloaded? Does this change avoid to use pods?

Thanks for you attention.

**Comment by foundry** [comment]
Hello Laura. Thanks for your interest in the project. This is really aimed for people like you, who are trying to get started with openCV on iOS. I found in the past that installing openCV and running a 'hello-world' level project was a prohibitively high hurdle to get going with this amazing framework. Once you have a base project working, it all becomes so much more interesting. 

To overcome installation issues, openCVSwiftStitch uses the iOS dependency manager [CocoaPods](https://cocoapods.org/), so you need to install that first (a fairly painless exercise).

When CocoPods is installed, `cd` to the project folder and run 'pod install'. A podfile is included in that folder that  cocoapods uses to find the right frameworks.

Following your comments, I  noticed that the  version you have is a little inconsistent: you should not have seen any references to pods (` ld: library not found for -lPods `) in the distribution, but it would have complained that it couldn't find the openCV framework. If you pull the latest commit, you will find a cleaner version. 

Once you have installed CocoaPods and  run `pod install` in the project folder,  you can run the project from  the `.SwiftStitch.xcworkspace` file that cocoapods creates.

I have updated the readme with a bit more information about this process, but you should find it just works.

Regarding OpenCV 3, I have not had the chance to test the new framework. Also it is not available via the pod distribution system yet.

When I have evaluated openCV3, I will either update the podfile, provide a new branch, or a new version as seems appropriate.

**Comment by foundry** [comment]
Update on last comment: I have tried the latest framework (3.0.0) by dragging it in to the latest version of SwiftStitch without bothering with CocoaPods, and it just works. if you had undergone the pain of installing previous versions, this is truly wonderful!. 

Also some hasty limited testing indicates that the stitching process around 85% faster (on an iPhone 5S).

**Comment by foundry** [comment]
OpenCV 3.0.0 does a faster but significantly poorer quality job on the sample. I've attached some images to the readme for comparison.

**Comment by LauraLaureus** [comment]
Thanks for answering ^^. I pulled the last version, run the "pod instal" and It works!
Another question: when you tried the last version of the library did you kept rest of code as it was?

Maybe you would like to know I'm using XCode 7-beta/prerelease with by default uses Swift 2.0 and it automaticly convert the Swift 1.2 code into 2.0 version and there weren't many changes, only a group of "var" clauses that were converted to "let" clauses, and It works, at least at simulator.

Thank you so much, I'm keep studying your code till I know pretty good.  :)

**Comment by foundry** [comment]
For OpenCV 3, I had to make a small change in to `stitching.cpp`  as the location and name of the openCV stitching header has changed.  I have left it in with a comment, so it should be quite clear what to do. Nothing else had to change  - much less trouble than I expected.

Thanks for letting me now about Swift 2, its good to know the update will be smooth. I will integrate with the project when it is out of beta. 

By the way, if you are new to OpenCV a good way to explore is to get the source code and look at the huge number of C++ samples  provided with the distribution (`stitching.cpp`  is lifted from one of those samples). With the objective-C wrapper technique, these are relatively easy to adapt: the basic approach is to change the i/o to pass through the wrapper, and leave the rest unchanged.

**Comment by LauraLaureus** [comment]
Thank you a lot for the help and for developing this example. Now I have my own project with the bridge and using Swift, Objective -C and C++ I'll take a look to the examples.
